name: My-extra-task

env:
 DEPLOY_VER: "deploy-version-${{  github.sha  }}"
 YEAR: 2022

on:
 push:
  branches:
   - master
   
jobs:
 extra-task1:
  runs-on: ubuntu-latest
  
  steps:
   - name: Git clone my repo
     uses: actions/checkout@v1
     
   - name: List all files
     run: ls -la
     
   - name: Print log file
     run: cat file5.txt
     

 
