name: favorite day

on:
  workflow_dispatch:
    inputs:
     fday:
        type: choice
        description: what is your favorite day?
        options: 
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday
jobs:
  favorite-day:
    runs-on: ubuntu-latest
    steps:
    - name: favorite day of week
      run: echo "${{ github.event.inputs.fday }}"
      
