name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
     fday:
        type: choise
        description: what is your favorite day?
        options: 
        - monday
        - tuesday

     
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: favorite day of week
      run: echo "${{ github.event.inputs.fday }} 
