name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      What-is-your-favorite-day-of-week:
        required: true
     
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: favorite day of week
      run: echo "${{ github.event.inputs.What-is-your-favorite-day-of-week }} 
